name: EP-Core
main: com.earthpol.epcore.Main
version: "1.0"
authors: ["0xBit"]
api: ["1.16.4"]
api-version: 1.16
depend: [ Towny ]
softdepend: [ TownyChat ]
description: EarthPols Main Core Listener and EventHandler Plugin.
website: https://earthpol.github.com